name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Build Backend
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up JDk 21
            uses: actions/setup-java@v2
            with:
                distribution: 'temurin'
                java-version: '21'

          - name: Build Backend
            run: |
              mvn clean install -DskipTests
              mvn package -DskipTests

          - name: deploy to azure
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'cvds-project'
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: /home/runner/work/cvds-project-be/cvds-project-be/target/LoginBack-0.0.1-SNAPSHOT.jar